"""add_model_column_to_providers

Revision ID: 5a8ec17ed340
Revises: 3f829b05495f
Create Date: 2026-02-26 20:36:48.987002+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5a8ec17ed340'
down_revision: Union[str, None] = '3f829b05495f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_providers', sa.Column('model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_providers', 'model')
    # ### end Alembic commands ###
